sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
install:
  - npm install
branches:
  only:
    - source # build source branch only
before_script:
  - sed -i s/GIT_TALK_OWNER/${GITHUB_REPO_TOKEN}/g  ./themes/pure/_config.yml
  - sed -i s/GIT_TALK_ADMIN/${GIT_TALK_ADMIN}/g  ./themes/pure/_config.yml
  - sed -i s/GIT_TALK_REPO/${GIT_TALK_REPO}/g  ./themes/pure/_config.yml
  - sed -i s/GIT_TALK_CLIENTID/${GIT_TALK_CLIENTID}/g  ./themes/pure/_config.yml
  - sed -i s/GIT_TALK_CLIENTSECRET/${GIT_TALK_CLIENTSECRET}/g  ./themes/pure/_config.yml
script:
  - hexo clean # clean static files
  - hexo generate # generate static files
after_script:
    - cd ./public
    - echo 'blog.uazw.com' > CNAME
    - git init
    - git config user.name "uazwu"
    - git config user.email "991552992@qq.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GITHUB_REPO_TOKEN}@github.com/uazwu/uazwu.github.io.git" master:master
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_REPO_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   local-dir: public
