sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
install:
  - npm install
branches:
  only:
    - source # build master branch only
script:
  - hexo clean # generate static files
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_REPO_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
